### ISSUE TITLE
5.15-2.2.x: lpuart still not working

### ISSUE THREAD

**Issue by jaskij** [Freescale/linux-fslc#623]
Since the fix and merge of #621  happened so fast, I was able to test it today. Sadly, it does not work. This time the results are different - no error happens, but console output just plain *stops* after some diagnostic messages from the driver.

This is the last of what I see:
```
[    1.198118] 5a060000.serial: ttyLP0 at MMIO 0x5a060010 (irq = 74, base_baud = 5000000) is a FSL_LPUART
[    1.208224] 5a070000.serial: ttyLP1 at MMIO 0x5a070010 (irq = 75, base_baud = 5000000) is a FSL_LPUART
```

I have no clue as to *why* this happens. What fixes this for me is moving `uart_add_one_port()` before `lpuart_global_reset()`. So, where before #621 there were two calls to `add_one_port()`, and the patch removed the first one while reordering cleanup, what works for me is removing the second call and leaving cleanup as-is.

If necessary, I can create a PR later tonight.

cc @otavio @MrCry0

**Comment by MrCry0** [comment]
@jaskij let me recheck it. The reorder was a part of the RS485 fix, and all other prerequisites to have this fix is in place.

**Comment by jaskij** [comment]
@MrCry0 for completeness sake, I'm using RS-232 for the console, not 485. To be specific, the default console on [conga-SMX8X](https://www.congatec.com/us/products/smarc/conga-smx8x/) (there's a transceiver and connector on the SoM, doesn't go through the baseboard).

**Comment by MrCry0** [comment]
> @MrCry0 for completeness sake, I'm using RS-232 for the console, not 485. To be specific, the default console on [conga-SMX8X](https://www.congatec.com/us/products/smarc/conga-smx8x/) (there's a transceiver and connector on the SoM, doesn't go through the baseboard).

I understand :) I mean the commit which introduces the second call of `uart_add_one_port()` and originally correct bases on a bunch of changes which all are in place in `5.15-2.2.x`. So just leaving the 1st call of `uart_add_one_port()` could be correct for your case and incorrect generally. I'm looking on it.

**Comment by MrCry0** [comment]
> @MrCry0 for completeness sake, I'm using RS-232 for the console, not 485. To be specific, the default console on [conga-SMX8X](https://www.congatec.com/us/products/smarc/conga-smx8x/) (there's a transceiver and connector on the SoM, doesn't go through the baseboard).

@jaskij Could you please test the fix https://github.com/Freescale/linux-fslc/pull/624

**Comment by jaskij** [comment]
Sure thing, will test soon.

As an additional comment, personally, I tend to not use RTS control via the peripheral, but just use GPIO RTS. Peripheral-controlled RTS has given me nothing but trouble in the past.

**Comment by jaskij** [comment]
@MrCry0 tested, #624 works.

**Comment by MrCry0** [comment]
> @MrCry0 tested, #624 works.

Thank you!

**Comment by angolini** [comment]
I think it's closed now, right?
In case it's still not closed, please reopen the issue.
