### ISSUE TITLE
mipi_dsi missing from imx8mm.dtsi

### ISSUE THREAD

**Issue by DominikPoggel** [Freescale/linux-fslc#633]
Is there a reason why the mipi_dsi node is missing from imx8mm.dtsi in linux-fslc while it is present in linux-fslc-imx? 
If it's missing for no reason, I will make a PR to resolve this

**Comment by otavio** [comment]
The `linux-fslc` uses the Linux mainline while the `linux-fslc-imx` uses Linux NXP fork.

**Comment by fabioestevam** [comment]
@DominikPoggel 

linux-next has mipi_dsi support on imx8mm and I have added support for HDMI on imx8mm-evk:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20230606&id=a27335b3f1e03fb3d0cdd28066b4d7d28e71e3a9

This will land in kernel version 6.5.
