### ISSUE TITLE
Issue to put kernel branch 4.9-1.0.x-imx in imx7d-pico with linux-fslc with Kernel 6.6

### ISSUE THREAD

**Issue by neuberfran** [Freescale/linux-fslc#648]
**Hi,

I stay running linux-fslc (Linux imx7d-pico 6.6.0-fslc-fslc-00010-g34836895e19e #1 SMP Mon Oct 30)
and U-Boot 2023.10+fslc+g105a9c8cc0 in my imx7d-pico device by TechNexion.
based in this tutorial: https://imxdev.gitlab.io/ann/The_imx7d-pico_board_is_now_supported_in_FSL_Community_BSP/

My problems start when I try to use rpmsg-lite.

Firstly I tried to insert the settings below in this kernel version and I was unable to do so:

> CONFIG_HAVE_IMX_MU=y
> CONFIG_HAVE_IMX_RPMSG=y
> CONFIG_RPMSG=y
> CONFIG_RPMSG_VIRTIO=y
> CONFIG_IMX_RPMSG_PINGPONG=m
> CONFIG_IMX_RPMSG_TTY=m

Afterwards (I've been trying for 2 weeks) I tried to put/port kernel 4.9-1.0.x-imx (https://github.com/diegosueiro/linux-fslc/tree/4.9-1.0.x-imx)

If the way mentioned above works, I will certainly be successful as the compilation of the zephyr-m4-side bin file is almost ready

Below are the errors I currently get when trying to port the kernel (from 6.6 to 4.9) and a screenshot**

E.g.: I'm putting the 4.9 kernel in a local folder on my computer (with all authorizations and permissions, ssh, git user, etc) and creating a *.bbappend with:
```
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI = "git://srv/git/linux.git;branch=scorpion_test2"
KBRANCH =  "scorpion_test2"
#SRCBRANCH =  "scorpion_test2"
##SRCPV  = "scorpion_test"
SRCREV = "${AUTOREV}"
```

**My issue is below:**
> 
> bitbake core-image-base
> Loading cache: 100% |#######################################################################################################################################################################| Time: 0:00:00
> Loaded 4377 entries from dependency cache.
> WARNING: /home/neuberfran/fsl-community-bsp/sources/meta-freescale/recipes-kernel/linux/linux-fslc_6.6.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc                | ETA:  --:--:--
> WARNING: /home/neuberfran/fsl-community-bsp/sources/meta-freescale/recipes-kernel/linux/linux-fslc_6.6.bb: Error during finalise of /home/neuberfran/fsl-community-bsp/sources/meta-freescale/recipes-kernel/linux/linux-fslc_6.6.bb
> ERROR: ExpansionError during parsing /home/neuberfran/fsl-community-bsp/sources/meta-freescale/recipes-kernel/linux/linux-fslc_6.6.bb
> Traceback (most recent call last):
>   File "/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 1241, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f11763795e0>, d=<bb.data_smart.DataSmart object at 0x7f117640bfd0>, name='default'):
>              d.setVar("__BBAUTOREV_ACTED_UPON", True)
>     >        srcrev = ud.method.latest_revision(ud, d, name)
>      
>   File "/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 1657, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f11763795e0>, d=<bb.data_smart.DataSmart object at 0x7f117640bfd0>, name='default'):
>              except KeyError:
>     >            revs[key] = rev = self._latest_revision(ud, d, name)
>                  return rev
>   File "/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/lib/bb/fetch2/git.py", line 773, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f11763795e0>, d=<bb.data_smart.DataSmart object at 0x7f117640bfd0>, name='default'):
>      
>     >        output = self._lsremote(ud, d, "")
>              # Tags of the form ^{} may not work, need to fallback to other form
>   File "/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/lib/bb/fetch2/git.py", line 756, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f11763795e0>, d=<bb.data_smart.DataSmart object at 0x7f117640bfd0>, search=''):
>                      bb.fetch2.check_network_access(d, cmd, repourl)
>     >            output = runfetchcmd(cmd, d, True)
>                  if not output:
>   File "/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 954, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1595"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/neuberfran/fsl-community-bsp/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/neuberfran/fsl-community-bsp/sources/poky/scripts:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/bin/arm-fslc-linux-gnueabi:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot/usr/bin/crossscripts:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/sbin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/bin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/sbin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/bin:/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/bin:/home/neuberfran/fsl-community-bsp/build/tmp/hosttools"; export HOME="/home/neuberfran"; git -c gc.autoDetach=false -c core.pager=cat ls-remote git://srv/git/linux.git ', d=<bb.data_smart.DataSmart object at 0x7f117640bfd0>, quiet=True, cleanup=[], log=None, workdir=None):
>      
>     >        raise FetchError(error_message)
>      
> bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1595"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/neuberfran/fsl-community-bsp/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/neuberfran/fsl-community-bsp/sources/poky/scripts:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/bin/arm-fslc-linux-gnueabi:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot/usr/bin/crossscripts:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/sbin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/usr/bin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/sbin:/home/neuberfran/fsl-community-bsp/build/tmp/work/imx7d_pico-fslc-linux-gnueabi/linux-fslc/6.6+git/recipe-sysroot-native/bin:/home/neuberfran/fsl-community-bsp/sources/poky/bitbake/bin:/home/neuberfran/fsl-community-bsp/build/tmp/hosttools"; export HOME="/home/neuberfran"; git -c gc.autoDetach=false -c core.pager=cat ls-remote git://srv/git/linux.git  failed with exit code 128, output:
> fatal: unable to look up srv (port 9418) (Temporary failure in name resolution)
> 
> The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]
> 
> ERROR: Parsing halted due to errors, see error messages above
> 
> Summary: There were 2 WARNING messages.
> Summary: There were 2 ERROR messages, returning a non-zero exit code.
> neuberfran@neuberfran2004:~/fsl-community-bsp/build$ bitbake core-image-base
> 
> 

![Captura de tela de 2023-11-15 20-39-34](https://github.com/Freescale/linux-fslc/assets/38701397/07c5c2a1-52f7-4565-ab77-8919d967d215)

**Comment by otavio** [comment]
The 4.9 is too old for use in current layers. See if it works in the current kernel as it is supported in mainline.

**Comment by neuberfran** [comment]
@otavio tks. When I said Firstly I tried to insert the settings below in this kernel version and I was unable to do so:

> CONFIG_HAVE_IMX_MU=y
> CONFIG_HAVE_IMX_RPMSG=y
> CONFIG_RPMSG=y
> CONFIG_RPMSG_VIRTIO=y
> CONFIG_IMX_RPMSG_PINGPONG=m
> CONFIG_IMX_RPMSG_TTY=m

What`s the best way to append it in .config Or defconfig in linux-fsl 6.6

**Comment by otavio** [comment]
Could you please check out this link: https://docs.yoctoproject.org/kernel-dev/common.html#creating-configuration-fragments? Although it's not directly related to our issue, I'm closing the ticket.
