### ISSUE TITLE
FSLC commits in 6.6-2.0.x -> 6.6-2.1.x

### ISSUE THREAD

**Issue by MaxKrummenacher** [Freescale/linux-fslc#691]
@angolini @otavio 

The FSLC fork of NXP's downstream kernel has a bunch of patches provided by the community which are not part of the bump to 6.6-2.1.x. Didn't they make it into 6.6-2.1.x on purpose?

I can cherry-pick and create a MR if they were forgotten but should go in.

```
git log --oneline --no-merges remotes/fslc/6.6-2.0.x-imx ^remotes/fslc/6.6-2.1.x-imx  
4d8a7fb526c1 imx8mp: Remove obsolete device tree file  
e420d14b057f MLK-25922-4 arm64: dts: imx93: add lpspi support  
965390eee531 Revert "dmaengine: fsl-edma: add address for channel mux register in fsl_edma_chan"  
a1553c4e0862 Revert "dmaengine: fsl-edma: add i.MX8ULP edma support"  
652e34468562 Revert "dmaengine: fsl-edma: clean up unused "fsl,imx8qm-adma" compatible string"  
f4114b5ea07c Revert "dmaengine: fsl-edma: change the memory access from local into remote mode in i.MX 8QM"  
97e602775143 Revert "arm64: dts: imx8-ss-conn: fix usdhc wrong lpcg clock order"  
dd280fd310dd arm64: imx_v8_defconfig: Enable CONFIG_GPIO_VF610  
d397e3e3c1a0 arm64: dts: imx8qm: add missing imx8-ss-cm40.dtsi include  
6fcf813eebb5 arm64: dts: imx8: img: add #address-cells and #size-cells to I2C MIPI CSI nodes  
f0597a382690 fw: imx: seco_mu: change dev_err to dev_err_probe for -EPROBE_DEFER  
918048ab95f8 clk: imx: imx8qm: add more resources to whitelist  
e6f85d2b4dce media: mxc_mipi_csi: improve style  
7a31ed76b4ee drm/imx: lcdifv3: Fix videomode settings  
fb5da09f0eae i2c: imx: Remove unnecessary clock reconfiguration  
```

From my judgement the following would be beneficial:
```
dd280fd310dd arm64: imx_v8_defconfig: Enable CONFIG_GPIO_VF610  
d397e3e3c1a0 arm64: dts: imx8qm: add missing imx8-ss-cm40.dtsi include  
6fcf813eebb5 arm64: dts: imx8: img: add #address-cells and #size-cells to I2C MIPI CSI nodes  
f0597a382690 fw: imx: seco_mu: change dev_err to dev_err_probe for -EPROBE_DEFER  
918048ab95f8 clk: imx: imx8qm: add more resources to whitelist  
7a31ed76b4ee drm/imx: lcdifv3: Fix videomode settings  
fb5da09f0eae i2c: imx: Remove unnecessary clock reconfiguration  
```

For the other commits:

I assume that the Reverts are all due to the stable merges and somehow
differently handled in 6.6-2.1.x.

The *.dtb removed gets created for me, probably the commit is not needed
`4d8a7fb526c1 imx8mp: Remove obsolete device tree file`

The following got reworked by NXP
`e420d14b057f MLK-25922-4 arm64: dts: imx93: add lpspi support`

This one is just code style but might make future stable merges harder
`e6f85d2b4dce media: mxc_mipi_csi: improve style`

**Comment by otavio** [comment]
This is just by mistake, so if you can prepare a PR, merging those would be of great help. We are trying to get more people to help to maintain the fork. So if you guys can be part of this effort, that would be a win-win partnership.

**Comment by MaxKrummenacher** [comment]
Done, closing the issue.
